---
threadCount: 1  # number threads which will handle sending and receiving of messages
summary: ./logs/summary.log  # file to which summary should be written
profile:
  - start: 0  # begin this testing profile item at, in milliseconds
    scenarios:  # list of scenarios used in this profile item
      - type: Demo  # type of the used scenario
        count: 1  # number of scenarios with particular type which will be spawned, in absolute numbers
  - start: 10000
    scenarios:
      - type: Demo
        count: 10
end: 20000  # when will the execution ends, in milliseconds
